spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: portfolio_user
    password: portfolio_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

docker:
  status:
    pubEndpoint: tcp://*:5556
